### ISSUE TITLE
Cannot instantiate project

### ISSUE THREAD

**Issue by petrposik** [sisl/algforopt-notebooks#10]
Hello.
(A newbie on Windows 10 here.)
I cloned the repo, entered Julia REPL, cd into the repo directory, and ran `]instantiate`
```
(algforopt-notebooks) pkg> instantiate
ERROR: expected package `TexExtensions [9b435220]` to be registered
```
I also tried to delete the main Registry, and redo, but it did not help. 
Any suggestion welcome.
Thanks a lot!

**Comment by tawheeler** [comment]
Maybe installing [TexExtensions](https://github.com/Keno/TexExtensions.jl) would cause it to be detected? The package certainly exists.
This is not a direct dependency of anything as far as I known. TexExtensions must be used by a package that we depend on.

**Comment by ilovejs** [comment]
/home/tim/.julia/dev/NGSIM

**Comment by tawheeler** [comment]
@ilovejs Does deleting those entries allow the package to be instantiated for you?

**Comment by tawheeler** [comment]
I recreated the Manifest.toml file. At some point we may want to upgrade to the newer Pkg format, but this should be fine for now.
