### ISSUE TITLE
Many multiobjective figures missing

### ISSUE THREAD

**Issue by tuncbkose** [sisl/algforopt-notebooks#12]
Hello.

Many figures from Chapter 12 are not included in the `multiobjective.ipynb` file. Of particular interest to me are Figure 12.5 and Figure 12.8, because I'd like to reproduce the non-convex set. It would be nice if they could be added to the file.

**Comment by tawheeler** [comment]
The .ipynb files only contain figures that were generated using Julia. Many of the figures in the multiobjective chapter were directly added via TikZ.

The shape from Fig 12.5 and 12.8 was generated with:

```
\fill[pastelBlue!40] (0.5,3.5)
	arc (180:270:1)
	arc (90:0:1)
	arc (180:270:1)
	[out=0, in=270] to (8,3)
	[out=90, in=0] to (4,5)
	[out=180, in=90] to cycle;
```
