### ISSUE TITLE
Cycle list delimiting

### ISSUE THREAD

**Issue by mykelk** [sisl/algforopt-notebooks#2]
In `support_code.jl`, shouldn't the lines that look like this
`pushPGFPlotsPreamble("  solid, pastelPurple, mark=none\\%")`
actually be
`pushPGFPlotsPreamble("  solid, pastelPurple, mark=none\\\\%")`
It looks like cycle lists need to be delimited by `\\`, which needs escaping in Julia.

**Comment by tawheeler** [comment]
Confirmed!
