### ISSUE TITLE
Notebook file for Chapter 3

### ISSUE THREAD

**Issue by KelvynCore** [sisl/algforopt-notebooks#4]
Could you provide the notebook related to chapter 3 please?

**Comment by tawheeler** [comment]
Chapter 3 is bracketing, [which is available here](https://github.com/sisl/algforopt-notebooks/blob/master/bracketing.ipynb). Please let me know if you cannot access it for some reason.

**Comment by tawheeler** [comment]
I'll close this for now. Please feel free to re-open if there is anything still to address.

**Comment by KelvynCore** [comment]
Sorry, Chapter 4

**Comment by tawheeler** [comment]
You are right - descent is missing. [I've uploaded it](https://github.com/sisl/algforopt-notebooks/blob/master/descent.ipynb).
