### ISSUE TITLE
prob-surrogate-models 

### ISSUE THREAD

**Issue by frank-ccc** [sisl/algforopt-notebooks#8]
Dear Tim,
Very sorry to bother you again.
The jupyter notebooks prob-surrogate-models seem to have a problem in outputting the plots in the first few cells (prior cases and later cells seem to work fine).
Thank you,
Frank

**Comment by tawheeler** [comment]
Thanks!
The exports are automated, and unfortunately there are also sometimes LaTeX definitions that have to manually be added. Looks like xfrac and mat were both needed. Should be fixed now.
