### ISSUE TITLE
expr notebook

### ISSUE THREAD

**Issue by frank-ccc** [sisl/algforopt-notebooks#9]
Hi there @tawheeler,
When running the expr Jupyter notebook it seems there is not eval method as I get 
`MethodError: no method matching eval(::RuleNode, ::Grammar)
`
Can you please help resolve this issue?
All the best,
FC

**Comment by tawheeler** [comment]
Hello Francesco. It looks like the latest versions of Julia distinguish between Core.eval, Base.eval, and Base.MainIncude.eval. Prepending Core. to the eval call fixes the problem.
I'll see whether we need to update the book code.
